name: Build

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        description: JDK version for gradle build
        required: false
        default: '17'
      java-distribution:
        type: string
        description: JDK distribution for gradle build
        required: false
        default: temurin
      use-configuration-cache:
        type: boolean
        description: Enable Gradle configuration cache
        required: false
        default: false
    secrets:
      nexus_url:
        description: Nexus base URL
        required: true
      nexus_username:
        description: Nexus username
        required: true
      nexus_password:
        description: Nexus password
        required: true

permissions:
  contents: read

jobs:
  wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - wrapper
    env:
      BASE_URL: ${{ github.server_url }}/${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Configuration
        run: |
          set -euo pipefail
          
          BUILD_PARAMS="-Prelease.useLastTag=$([[ "${GITHUB_REF}" = refs/tags/v* ]] && echo true || echo false)"
          [[ "${CONFIGURATION_CACHE}" = true ]] && BUILD_PARAMS="${BUILD_PARAMS} --configuration-cache"
          echo "BUILD_PARAMS=${BUILD_PARAMS}" >> ${GITHUB_ENV}
          
          ID=${GITHUB_REF_NAME:-$GITHUB_SHA}
          URL=${BASE_URL}/tree/${ID}
          if [[ ${GITHUB_EVENT_NAME} = pull_request ]] ; then
            ID=${ID%/*} # keep only PR number
            URL=${BASE_URL}/pulls/${ID}
          fi
          
          case ${GITHUB_EVENT_NAME}:${GITHUB_REF_TYPE}:${GITHUB_REF_NAME} in
            push:tag:v*) TYPE="Release" ;;
            push:branch:*) TYPE="Branch" ;;
            pull_request:*) TYPE="PR" ;;
            *) TYPE="Tag" ;;
          esac
          echo "REF_DESC=${TYPE} <${URL}|\`${ID}\`>" >> ${GITHUB_ENV}
        env:
          CONFIGURATION_CACHE: ${{ inputs.use-configuration-cache }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build
        id: gradle-build
        run: |
          ./gradlew assemble \
            ${{ env.BUILD_PARAMS }} \
            -PnexusUrl=${{ secrets.nexus_url }} \
            -PnexusUsername=${{ secrets.nexus_username }} \
            -PnexusPassword=${{ secrets.nexus_password }}

      - name: Run tests and checks
        id: gradle-check
        run: |
          ./gradlew check \
            ${{ env.BUILD_PARAMS }} \
            -PnexusUrl=${{ secrets.nexus_url }} \
            -PnexusUsername=${{ secrets.nexus_username }} \
            -PnexusPassword=${{ secrets.nexus_password }}
