name: CI

on:
  pull_request:
    paths-ignore:
      - '**.adoc'
  push:
    branches:
      - main
      - 'releases/*'
    paths-ignore:
      - '**.adoc'

jobs:
  build:
    name: Build all actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install yarn
        if: ${{ env.ACT }}
        run: npm -g install yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        if: ${{ !env.ACT }}
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn run format-check

      - name: ESLint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Package
        run: yarn run package

      - name: Verify dist/ is committed and up-to-date
        if: ${{ !env.ACT }}
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            echo ----------------------------------------
            echo git status
            echo ----------------------------------------
            git status
            echo ----------------------------------------
            echo git diff
            echo ----------------------------------------
            git diff
            echo ----------------------------------------
            echo Troubleshooting
            echo ----------------------------------------
            echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && npm ci && npm run pre-checkin"
            exit 1
          fi

  test-find-prs:
    name: Test find-prs action
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v2

      - uses: ./find-prs
        id: find-prs
        with:
          commit-sha: ${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Action output
        run: echo '${{ steps.find-prs.outputs.prs }}' | jq .

  test-nexus:
    name: Test nexus aciton
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v2

      - uses: ./nexus
        id: nexus
        with:
          base-url: https://nexus.example.com
          repos: |
            [ {
              "id": "nexus",
              "repo": "public",
              "auth": true,
              "releases": {"enabled": true, "checksumPolicy": "warn"},
              "snapshots": {"enabled": true, "checksumPolicy": "warn"}
            }, {
              "id": "nexus-thirdparty",
              "repo": "thirdparty",
              "auth": true,
              "releases": {"enabled": true, "checksumPolicy": "warn"},
              "snapshots": {"enabled": false}
            } ]
          plugin-repos: |
            [ {
              "id": "nexus",
              "repo": "public",
              "auth": true,
              "releases": {"enabled": true, "checksumPolicy": "warn"},
              "snapshots": {"enabled": false}
            } ]
      - name: Action output
        run: cat ~/.m2/settings.xml
