name: Release

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        description: JDK version for gradle build
        required: false
        default: '17'
      java-distribution:
        type: string
        description: JDK distribution for gradle build
        required: false
        default: temurin
    secrets:
      nexus-url:
        description: Nexus base URL
        required: true
      nexus-username:
        description: Nexus username
        required: true
      nexus-password:
        description: Nexus password
        required: true

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ github.server_url }}/${{ github.repository }}

    steps:
      - name: Preconditions check
        run: |
          if [[ $GITHUB_REF != refs/tags/v* ]] ; then
            echo "Expected refs/tags/v* but got ${GITHUB_REF}"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Publish
        id: gradle-publish
        run: |
          ./gradlew publish \
            -Prelease.useLastTag=true \
            -PnexusUrl=${{ secrets.nexus-url }} \
            -PnexusUsername=${{ secrets.nexus-username }} \
            -PnexusPassword=${{ secrets.nexus-password }}
