name: Release

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        description: JDK version for gradle build
        required: false
        default: '17'
      java-distribution:
        type: string
        description: JDK distribution for gradle build
        required: false
        default: temurin
    secrets:
      nexus_url:
        description: Nexus base URL
        required: true
      nexus_username:
        description: Nexus username
        required: true
      nexus_password:
        description: Nexus password
        required: true
      zulip_api_key:
        description: Zulip bot api key
        required: false
      zulip_email:
        description: Zulip bot email
        required: false
      zulip_url:
        description: Zulip organization URL
        required: false

permissions:
  contents: read

env:
  ZULIP_URL: ${{ secrets.zulip_url }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ github.server_url }}/${{ github.repository }}

    steps:
      - name: Preconditions check
        run: |
          if [[ $GITHUB_REF != refs/tags/v* ]] ; then
            echo "Expected refs/tags/v* but got ${GITHUB_REF}"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Zulip notification
        uses: zulip/github-actions-zulip/send-message@v1
        if: ${{ !!env.ZULIP_URL && always() }}
        with:
          api-key: ${{ secrets.zulip_api_key }}
          email: ${{ secrets.zulip_email }}
          organization-url: ${{ secrets.zulip_url }}
          type: stream
          to: dev
          topic: GitHub Notifications
          content: |
            **${{ github.repository }}** release ${{ github.ref_name }} *started*

            Release [`${{ github.ref_name }}`](${{ env.BASE_URL }}/tree/${{ github.ref_name }})

            JDK: *${{ inputs.java-version }}* (${{ inputs.java-distribution }})

            Workflow run ${{ env.BASE_URL }}/actions/runs/${{ github.run_id }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Publish
        id: gradle-publish
        run: |
          ./gradlew publish \
            -Prelease.useLastTag=true \
            -PnexusUrl=${{ secrets.nexus_url }} \
            -PnexusUsername=${{ secrets.nexus_username }} \
            -PnexusPassword=${{ secrets.nexus_password }}

      - name: Zulip notification
        uses: zulip/github-actions-zulip/send-message@v1
        if: ${{ !!env.ZULIP_URL && always() }}
        with:
          api-key: ${{ secrets.zulip_api_key }}
          email: ${{ secrets.zulip_email }}
          organization-url: ${{ secrets.zulip_url }}
          type: stream
          to: dev
          topic: GitHub Notifications
          content: |
            **${{ github.repository }}** release ${{ github.ref_name }} *${{ job.status }}*

            Release [`${{ github.ref_name }}`](${{ env.BASE_URL }}/tree/${{ github.ref_name }})

            JDK: *${{ inputs.java-version }}* (${{ inputs.java-distribution }})

            Workflow run ${{ env.BASE_URL }}/actions/runs/${{ github.run_id }}
